// Code generated by ent, DO NOT EDIT.

package promptrule

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldDescription, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldEnabled, v))
}

// Order applies equality check predicate on the "order" field. It's identical to OrderEQ.
func Order(v int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldOrder, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldRole, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldContent, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldAction, v))
}

// MatchPattern applies equality check predicate on the "match_pattern" field. It's identical to MatchPatternEQ.
func MatchPattern(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldMatchPattern, v))
}

// MatchMode applies equality check predicate on the "match_mode" field. It's identical to MatchModeEQ.
func MatchMode(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldMatchMode, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContainsFold(FieldDescription, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldEnabled, v))
}

// OrderEQ applies the EQ predicate on the "order" field.
func OrderEQ(v int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldOrder, v))
}

// OrderNEQ applies the NEQ predicate on the "order" field.
func OrderNEQ(v int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldOrder, v))
}

// OrderIn applies the In predicate on the "order" field.
func OrderIn(vs ...int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldOrder, vs...))
}

// OrderNotIn applies the NotIn predicate on the "order" field.
func OrderNotIn(vs ...int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldOrder, vs...))
}

// OrderGT applies the GT predicate on the "order" field.
func OrderGT(v int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldOrder, v))
}

// OrderGTE applies the GTE predicate on the "order" field.
func OrderGTE(v int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldOrder, v))
}

// OrderLT applies the LT predicate on the "order" field.
func OrderLT(v int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldOrder, v))
}

// OrderLTE applies the LTE predicate on the "order" field.
func OrderLTE(v int) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldOrder, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContainsFold(FieldRole, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContainsFold(FieldContent, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContainsFold(FieldAction, v))
}

// MatchPatternEQ applies the EQ predicate on the "match_pattern" field.
func MatchPatternEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldMatchPattern, v))
}

// MatchPatternNEQ applies the NEQ predicate on the "match_pattern" field.
func MatchPatternNEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldMatchPattern, v))
}

// MatchPatternIn applies the In predicate on the "match_pattern" field.
func MatchPatternIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldMatchPattern, vs...))
}

// MatchPatternNotIn applies the NotIn predicate on the "match_pattern" field.
func MatchPatternNotIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldMatchPattern, vs...))
}

// MatchPatternGT applies the GT predicate on the "match_pattern" field.
func MatchPatternGT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldMatchPattern, v))
}

// MatchPatternGTE applies the GTE predicate on the "match_pattern" field.
func MatchPatternGTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldMatchPattern, v))
}

// MatchPatternLT applies the LT predicate on the "match_pattern" field.
func MatchPatternLT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldMatchPattern, v))
}

// MatchPatternLTE applies the LTE predicate on the "match_pattern" field.
func MatchPatternLTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldMatchPattern, v))
}

// MatchPatternContains applies the Contains predicate on the "match_pattern" field.
func MatchPatternContains(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContains(FieldMatchPattern, v))
}

// MatchPatternHasPrefix applies the HasPrefix predicate on the "match_pattern" field.
func MatchPatternHasPrefix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasPrefix(FieldMatchPattern, v))
}

// MatchPatternHasSuffix applies the HasSuffix predicate on the "match_pattern" field.
func MatchPatternHasSuffix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasSuffix(FieldMatchPattern, v))
}

// MatchPatternIsNil applies the IsNil predicate on the "match_pattern" field.
func MatchPatternIsNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIsNull(FieldMatchPattern))
}

// MatchPatternNotNil applies the NotNil predicate on the "match_pattern" field.
func MatchPatternNotNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotNull(FieldMatchPattern))
}

// MatchPatternEqualFold applies the EqualFold predicate on the "match_pattern" field.
func MatchPatternEqualFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEqualFold(FieldMatchPattern, v))
}

// MatchPatternContainsFold applies the ContainsFold predicate on the "match_pattern" field.
func MatchPatternContainsFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContainsFold(FieldMatchPattern, v))
}

// MatchModeEQ applies the EQ predicate on the "match_mode" field.
func MatchModeEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEQ(FieldMatchMode, v))
}

// MatchModeNEQ applies the NEQ predicate on the "match_mode" field.
func MatchModeNEQ(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNEQ(FieldMatchMode, v))
}

// MatchModeIn applies the In predicate on the "match_mode" field.
func MatchModeIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIn(FieldMatchMode, vs...))
}

// MatchModeNotIn applies the NotIn predicate on the "match_mode" field.
func MatchModeNotIn(vs ...string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotIn(FieldMatchMode, vs...))
}

// MatchModeGT applies the GT predicate on the "match_mode" field.
func MatchModeGT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGT(FieldMatchMode, v))
}

// MatchModeGTE applies the GTE predicate on the "match_mode" field.
func MatchModeGTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldGTE(FieldMatchMode, v))
}

// MatchModeLT applies the LT predicate on the "match_mode" field.
func MatchModeLT(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLT(FieldMatchMode, v))
}

// MatchModeLTE applies the LTE predicate on the "match_mode" field.
func MatchModeLTE(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldLTE(FieldMatchMode, v))
}

// MatchModeContains applies the Contains predicate on the "match_mode" field.
func MatchModeContains(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContains(FieldMatchMode, v))
}

// MatchModeHasPrefix applies the HasPrefix predicate on the "match_mode" field.
func MatchModeHasPrefix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasPrefix(FieldMatchMode, v))
}

// MatchModeHasSuffix applies the HasSuffix predicate on the "match_mode" field.
func MatchModeHasSuffix(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldHasSuffix(FieldMatchMode, v))
}

// MatchModeIsNil applies the IsNil predicate on the "match_mode" field.
func MatchModeIsNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIsNull(FieldMatchMode))
}

// MatchModeNotNil applies the NotNil predicate on the "match_mode" field.
func MatchModeNotNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotNull(FieldMatchMode))
}

// MatchModeEqualFold applies the EqualFold predicate on the "match_mode" field.
func MatchModeEqualFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldEqualFold(FieldMatchMode, v))
}

// MatchModeContainsFold applies the ContainsFold predicate on the "match_mode" field.
func MatchModeContainsFold(v string) predicate.PromptRule {
	return predicate.PromptRule(sql.FieldContainsFold(FieldMatchMode, v))
}

// GroupIdsIsNil applies the IsNil predicate on the "group_ids" field.
func GroupIdsIsNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIsNull(FieldGroupIds))
}

// GroupIdsNotNil applies the NotNil predicate on the "group_ids" field.
func GroupIdsNotNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotNull(FieldGroupIds))
}

// ModelIdsIsNil applies the IsNil predicate on the "model_ids" field.
func ModelIdsIsNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldIsNull(FieldModelIds))
}

// ModelIdsNotNil applies the NotNil predicate on the "model_ids" field.
func ModelIdsNotNil() predicate.PromptRule {
	return predicate.PromptRule(sql.FieldNotNull(FieldModelIds))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromptRule) predicate.PromptRule {
	return predicate.PromptRule(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromptRule) predicate.PromptRule {
	return predicate.PromptRule(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromptRule) predicate.PromptRule {
	return predicate.PromptRule(sql.NotPredicates(p))
}
