// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/promptrule"
)

// PromptRule is the model entity for the PromptRule schema.
type PromptRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Order holds the value of the "order" field.
	Order int `json:"order,omitempty"`
	// Role holds the value of the "role" field.
	Role string `json:"role,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// MatchPattern holds the value of the "match_pattern" field.
	MatchPattern *string `json:"match_pattern,omitempty"`
	// MatchMode holds the value of the "match_mode" field.
	MatchMode string `json:"match_mode,omitempty"`
	// GroupIds holds the value of the "group_ids" field.
	GroupIds []int64 `json:"group_ids,omitempty"`
	// ModelIds holds the value of the "model_ids" field.
	ModelIds     []string `json:"model_ids,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromptRule) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promptrule.FieldGroupIds, promptrule.FieldModelIds:
			values[i] = new([]byte)
		case promptrule.FieldEnabled:
			values[i] = new(sql.NullBool)
		case promptrule.FieldID, promptrule.FieldOrder:
			values[i] = new(sql.NullInt64)
		case promptrule.FieldName, promptrule.FieldDescription, promptrule.FieldRole, promptrule.FieldContent, promptrule.FieldAction, promptrule.FieldMatchPattern, promptrule.FieldMatchMode:
			values[i] = new(sql.NullString)
		case promptrule.FieldCreatedAt, promptrule.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromptRule fields.
func (_m *PromptRule) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promptrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case promptrule.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case promptrule.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case promptrule.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case promptrule.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case promptrule.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case promptrule.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				_m.Order = int(value.Int64)
			}
		case promptrule.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case promptrule.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				_m.Content = value.String
			}
		case promptrule.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case promptrule.FieldMatchPattern:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_pattern", values[i])
			} else if value.Valid {
				_m.MatchPattern = new(string)
				*_m.MatchPattern = value.String
			}
		case promptrule.FieldMatchMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field match_mode", values[i])
			} else if value.Valid {
				_m.MatchMode = value.String
			}
		case promptrule.FieldGroupIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field group_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GroupIds); err != nil {
					return fmt.Errorf("unmarshal field group_ids: %w", err)
				}
			}
		case promptrule.FieldModelIds:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field model_ids", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ModelIds); err != nil {
					return fmt.Errorf("unmarshal field model_ids: %w", err)
				}
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromptRule.
// This includes values selected through modifiers, order, etc.
func (_m *PromptRule) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PromptRule.
// Note that you need to call PromptRule.Unwrap() before calling this method if this PromptRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromptRule) Update() *PromptRuleUpdateOne {
	return NewPromptRuleClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromptRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromptRule) Unwrap() *PromptRule {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromptRule is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromptRule) String() string {
	var builder strings.Builder
	builder.WriteString("PromptRule(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("order=")
	builder.WriteString(fmt.Sprintf("%v", _m.Order))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(_m.Content)
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	if v := _m.MatchPattern; v != nil {
		builder.WriteString("match_pattern=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("match_mode=")
	builder.WriteString(_m.MatchMode)
	builder.WriteString(", ")
	builder.WriteString("group_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupIds))
	builder.WriteString(", ")
	builder.WriteString("model_ids=")
	builder.WriteString(fmt.Sprintf("%v", _m.ModelIds))
	builder.WriteByte(')')
	return builder.String()
}

// PromptRules is a parsable slice of PromptRule.
type PromptRules []*PromptRule
