// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promptrule"
)

// PromptRuleCreate is the builder for creating a PromptRule entity.
type PromptRuleCreate struct {
	config
	mutation *PromptRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptRuleCreate) SetCreatedAt(v time.Time) *PromptRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableCreatedAt(v *time.Time) *PromptRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromptRuleCreate) SetUpdatedAt(v time.Time) *PromptRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableUpdatedAt(v *time.Time) *PromptRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *PromptRuleCreate) SetName(v string) *PromptRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PromptRuleCreate) SetDescription(v string) *PromptRuleCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableDescription(v *string) *PromptRuleCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *PromptRuleCreate) SetEnabled(v bool) *PromptRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableEnabled(v *bool) *PromptRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetOrder sets the "order" field.
func (_c *PromptRuleCreate) SetOrder(v int) *PromptRuleCreate {
	_c.mutation.SetOrder(v)
	return _c
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableOrder(v *int) *PromptRuleCreate {
	if v != nil {
		_c.SetOrder(*v)
	}
	return _c
}

// SetRole sets the "role" field.
func (_c *PromptRuleCreate) SetRole(v string) *PromptRuleCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableRole(v *string) *PromptRuleCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *PromptRuleCreate) SetContent(v string) *PromptRuleCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetAction sets the "action" field.
func (_c *PromptRuleCreate) SetAction(v string) *PromptRuleCreate {
	_c.mutation.SetAction(v)
	return _c
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableAction(v *string) *PromptRuleCreate {
	if v != nil {
		_c.SetAction(*v)
	}
	return _c
}

// SetMatchPattern sets the "match_pattern" field.
func (_c *PromptRuleCreate) SetMatchPattern(v string) *PromptRuleCreate {
	_c.mutation.SetMatchPattern(v)
	return _c
}

// SetNillableMatchPattern sets the "match_pattern" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableMatchPattern(v *string) *PromptRuleCreate {
	if v != nil {
		_c.SetMatchPattern(*v)
	}
	return _c
}

// SetMatchMode sets the "match_mode" field.
func (_c *PromptRuleCreate) SetMatchMode(v string) *PromptRuleCreate {
	_c.mutation.SetMatchMode(v)
	return _c
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_c *PromptRuleCreate) SetNillableMatchMode(v *string) *PromptRuleCreate {
	if v != nil {
		_c.SetMatchMode(*v)
	}
	return _c
}

// SetGroupIds sets the "group_ids" field.
func (_c *PromptRuleCreate) SetGroupIds(v []int64) *PromptRuleCreate {
	_c.mutation.SetGroupIds(v)
	return _c
}

// SetModelIds sets the "model_ids" field.
func (_c *PromptRuleCreate) SetModelIds(v []string) *PromptRuleCreate {
	_c.mutation.SetModelIds(v)
	return _c
}

// Mutation returns the PromptRuleMutation object of the builder.
func (_c *PromptRuleCreate) Mutation() *PromptRuleMutation {
	return _c.mutation
}

// Save creates the PromptRule in the database.
func (_c *PromptRuleCreate) Save(ctx context.Context) (*PromptRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptRuleCreate) SaveX(ctx context.Context) *PromptRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promptrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promptrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := promptrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.Order(); !ok {
		v := promptrule.DefaultOrder
		_c.mutation.SetOrder(v)
	}
	if _, ok := _c.mutation.Role(); !ok {
		v := promptrule.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Action(); !ok {
		v := promptrule.DefaultAction
		_c.mutation.SetAction(v)
	}
	if _, ok := _c.mutation.MatchMode(); !ok {
		v := promptrule.DefaultMatchMode
		_c.mutation.SetMatchMode(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromptRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromptRule.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "PromptRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := promptrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromptRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "PromptRule.enabled"`)}
	}
	if _, ok := _c.mutation.Order(); !ok {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required field "PromptRule.order"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "PromptRule.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := promptrule.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "PromptRule.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "PromptRule.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := promptrule.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "PromptRule.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Action(); !ok {
		return &ValidationError{Name: "action", err: errors.New(`ent: missing required field "PromptRule.action"`)}
	}
	if v, ok := _c.mutation.Action(); ok {
		if err := promptrule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "PromptRule.action": %w`, err)}
		}
	}
	if v, ok := _c.mutation.MatchMode(); ok {
		if err := promptrule.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "PromptRule.match_mode": %w`, err)}
		}
	}
	return nil
}

func (_c *PromptRuleCreate) sqlSave(ctx context.Context) (*PromptRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptRuleCreate) createSpec() (*PromptRule, *sqlgraph.CreateSpec) {
	var (
		_node = &PromptRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promptrule.Table, sqlgraph.NewFieldSpec(promptrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promptrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promptrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(promptrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(promptrule.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(promptrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Order(); ok {
		_spec.SetField(promptrule.FieldOrder, field.TypeInt, value)
		_node.Order = value
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(promptrule.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(promptrule.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Action(); ok {
		_spec.SetField(promptrule.FieldAction, field.TypeString, value)
		_node.Action = value
	}
	if value, ok := _c.mutation.MatchPattern(); ok {
		_spec.SetField(promptrule.FieldMatchPattern, field.TypeString, value)
		_node.MatchPattern = &value
	}
	if value, ok := _c.mutation.MatchMode(); ok {
		_spec.SetField(promptrule.FieldMatchMode, field.TypeString, value)
		_node.MatchMode = value
	}
	if value, ok := _c.mutation.GroupIds(); ok {
		_spec.SetField(promptrule.FieldGroupIds, field.TypeJSON, value)
		_node.GroupIds = value
	}
	if value, ok := _c.mutation.ModelIds(); ok {
		_spec.SetField(promptrule.FieldModelIds, field.TypeJSON, value)
		_node.ModelIds = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptRuleCreate) OnConflict(opts ...sql.ConflictOption) *PromptRuleUpsertOne {
	_c.conflict = opts
	return &PromptRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptRuleCreate) OnConflictColumns(columns ...string) *PromptRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptRuleUpsertOne{
		create: _c,
	}
}

type (
	// PromptRuleUpsertOne is the builder for "upsert"-ing
	//  one PromptRule node.
	PromptRuleUpsertOne struct {
		create *PromptRuleCreate
	}

	// PromptRuleUpsert is the "OnConflict" setter.
	PromptRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptRuleUpsert) SetUpdatedAt(v time.Time) *PromptRuleUpsert {
	u.Set(promptrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateUpdatedAt() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *PromptRuleUpsert) SetName(v string) *PromptRuleUpsert {
	u.Set(promptrule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateName() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldName)
	return u
}

// SetDescription sets the "description" field.
func (u *PromptRuleUpsert) SetDescription(v string) *PromptRuleUpsert {
	u.Set(promptrule.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateDescription() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *PromptRuleUpsert) ClearDescription() *PromptRuleUpsert {
	u.SetNull(promptrule.FieldDescription)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *PromptRuleUpsert) SetEnabled(v bool) *PromptRuleUpsert {
	u.Set(promptrule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateEnabled() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldEnabled)
	return u
}

// SetOrder sets the "order" field.
func (u *PromptRuleUpsert) SetOrder(v int) *PromptRuleUpsert {
	u.Set(promptrule.FieldOrder, v)
	return u
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateOrder() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldOrder)
	return u
}

// AddOrder adds v to the "order" field.
func (u *PromptRuleUpsert) AddOrder(v int) *PromptRuleUpsert {
	u.Add(promptrule.FieldOrder, v)
	return u
}

// SetRole sets the "role" field.
func (u *PromptRuleUpsert) SetRole(v string) *PromptRuleUpsert {
	u.Set(promptrule.FieldRole, v)
	return u
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateRole() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldRole)
	return u
}

// SetContent sets the "content" field.
func (u *PromptRuleUpsert) SetContent(v string) *PromptRuleUpsert {
	u.Set(promptrule.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateContent() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldContent)
	return u
}

// SetAction sets the "action" field.
func (u *PromptRuleUpsert) SetAction(v string) *PromptRuleUpsert {
	u.Set(promptrule.FieldAction, v)
	return u
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateAction() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldAction)
	return u
}

// SetMatchPattern sets the "match_pattern" field.
func (u *PromptRuleUpsert) SetMatchPattern(v string) *PromptRuleUpsert {
	u.Set(promptrule.FieldMatchPattern, v)
	return u
}

// UpdateMatchPattern sets the "match_pattern" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateMatchPattern() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldMatchPattern)
	return u
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (u *PromptRuleUpsert) ClearMatchPattern() *PromptRuleUpsert {
	u.SetNull(promptrule.FieldMatchPattern)
	return u
}

// SetMatchMode sets the "match_mode" field.
func (u *PromptRuleUpsert) SetMatchMode(v string) *PromptRuleUpsert {
	u.Set(promptrule.FieldMatchMode, v)
	return u
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateMatchMode() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldMatchMode)
	return u
}

// ClearMatchMode clears the value of the "match_mode" field.
func (u *PromptRuleUpsert) ClearMatchMode() *PromptRuleUpsert {
	u.SetNull(promptrule.FieldMatchMode)
	return u
}

// SetGroupIds sets the "group_ids" field.
func (u *PromptRuleUpsert) SetGroupIds(v []int64) *PromptRuleUpsert {
	u.Set(promptrule.FieldGroupIds, v)
	return u
}

// UpdateGroupIds sets the "group_ids" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateGroupIds() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldGroupIds)
	return u
}

// ClearGroupIds clears the value of the "group_ids" field.
func (u *PromptRuleUpsert) ClearGroupIds() *PromptRuleUpsert {
	u.SetNull(promptrule.FieldGroupIds)
	return u
}

// SetModelIds sets the "model_ids" field.
func (u *PromptRuleUpsert) SetModelIds(v []string) *PromptRuleUpsert {
	u.Set(promptrule.FieldModelIds, v)
	return u
}

// UpdateModelIds sets the "model_ids" field to the value that was provided on create.
func (u *PromptRuleUpsert) UpdateModelIds() *PromptRuleUpsert {
	u.SetExcluded(promptrule.FieldModelIds)
	return u
}

// ClearModelIds clears the value of the "model_ids" field.
func (u *PromptRuleUpsert) ClearModelIds() *PromptRuleUpsert {
	u.SetNull(promptrule.FieldModelIds)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromptRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptRuleUpsertOne) UpdateNewValues() *PromptRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promptrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromptRuleUpsertOne) Ignore() *PromptRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptRuleUpsertOne) DoNothing() *PromptRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptRuleCreate.OnConflict
// documentation for more info.
func (u *PromptRuleUpsertOne) Update(set func(*PromptRuleUpsert)) *PromptRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptRuleUpsertOne) SetUpdatedAt(v time.Time) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateUpdatedAt() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *PromptRuleUpsertOne) SetName(v string) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateName() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *PromptRuleUpsertOne) SetDescription(v string) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateDescription() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PromptRuleUpsertOne) ClearDescription() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PromptRuleUpsertOne) SetEnabled(v bool) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateEnabled() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetOrder sets the "order" field.
func (u *PromptRuleUpsertOne) SetOrder(v int) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetOrder(v)
	})
}

// AddOrder adds v to the "order" field.
func (u *PromptRuleUpsertOne) AddOrder(v int) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.AddOrder(v)
	})
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateOrder() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateOrder()
	})
}

// SetRole sets the "role" field.
func (u *PromptRuleUpsertOne) SetRole(v string) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateRole() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *PromptRuleUpsertOne) SetContent(v string) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateContent() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateContent()
	})
}

// SetAction sets the "action" field.
func (u *PromptRuleUpsertOne) SetAction(v string) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateAction() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateAction()
	})
}

// SetMatchPattern sets the "match_pattern" field.
func (u *PromptRuleUpsertOne) SetMatchPattern(v string) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetMatchPattern(v)
	})
}

// UpdateMatchPattern sets the "match_pattern" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateMatchPattern() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateMatchPattern()
	})
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (u *PromptRuleUpsertOne) ClearMatchPattern() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearMatchPattern()
	})
}

// SetMatchMode sets the "match_mode" field.
func (u *PromptRuleUpsertOne) SetMatchMode(v string) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetMatchMode(v)
	})
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateMatchMode() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateMatchMode()
	})
}

// ClearMatchMode clears the value of the "match_mode" field.
func (u *PromptRuleUpsertOne) ClearMatchMode() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearMatchMode()
	})
}

// SetGroupIds sets the "group_ids" field.
func (u *PromptRuleUpsertOne) SetGroupIds(v []int64) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetGroupIds(v)
	})
}

// UpdateGroupIds sets the "group_ids" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateGroupIds() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateGroupIds()
	})
}

// ClearGroupIds clears the value of the "group_ids" field.
func (u *PromptRuleUpsertOne) ClearGroupIds() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearGroupIds()
	})
}

// SetModelIds sets the "model_ids" field.
func (u *PromptRuleUpsertOne) SetModelIds(v []string) *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetModelIds(v)
	})
}

// UpdateModelIds sets the "model_ids" field to the value that was provided on create.
func (u *PromptRuleUpsertOne) UpdateModelIds() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateModelIds()
	})
}

// ClearModelIds clears the value of the "model_ids" field.
func (u *PromptRuleUpsertOne) ClearModelIds() *PromptRuleUpsertOne {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearModelIds()
	})
}

// Exec executes the query.
func (u *PromptRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromptRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromptRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromptRuleCreateBulk is the builder for creating many PromptRule entities in bulk.
type PromptRuleCreateBulk struct {
	config
	err      error
	builders []*PromptRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the PromptRule entities in the database.
func (_c *PromptRuleCreateBulk) Save(ctx context.Context) ([]*PromptRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromptRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptRuleCreateBulk) SaveX(ctx context.Context) []*PromptRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromptRuleUpsertBulk {
	_c.conflict = opts
	return &PromptRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptRuleCreateBulk) OnConflictColumns(columns ...string) *PromptRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptRuleUpsertBulk{
		create: _c,
	}
}

// PromptRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of PromptRule nodes.
type PromptRuleUpsertBulk struct {
	create *PromptRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromptRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptRuleUpsertBulk) UpdateNewValues() *PromptRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promptrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromptRuleUpsertBulk) Ignore() *PromptRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptRuleUpsertBulk) DoNothing() *PromptRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptRuleCreateBulk.OnConflict
// documentation for more info.
func (u *PromptRuleUpsertBulk) Update(set func(*PromptRuleUpsert)) *PromptRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptRuleUpsertBulk) SetUpdatedAt(v time.Time) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateUpdatedAt() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *PromptRuleUpsertBulk) SetName(v string) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateName() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateName()
	})
}

// SetDescription sets the "description" field.
func (u *PromptRuleUpsertBulk) SetDescription(v string) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateDescription() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *PromptRuleUpsertBulk) ClearDescription() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearDescription()
	})
}

// SetEnabled sets the "enabled" field.
func (u *PromptRuleUpsertBulk) SetEnabled(v bool) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateEnabled() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateEnabled()
	})
}

// SetOrder sets the "order" field.
func (u *PromptRuleUpsertBulk) SetOrder(v int) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetOrder(v)
	})
}

// AddOrder adds v to the "order" field.
func (u *PromptRuleUpsertBulk) AddOrder(v int) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.AddOrder(v)
	})
}

// UpdateOrder sets the "order" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateOrder() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateOrder()
	})
}

// SetRole sets the "role" field.
func (u *PromptRuleUpsertBulk) SetRole(v string) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetRole(v)
	})
}

// UpdateRole sets the "role" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateRole() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateRole()
	})
}

// SetContent sets the "content" field.
func (u *PromptRuleUpsertBulk) SetContent(v string) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateContent() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateContent()
	})
}

// SetAction sets the "action" field.
func (u *PromptRuleUpsertBulk) SetAction(v string) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetAction(v)
	})
}

// UpdateAction sets the "action" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateAction() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateAction()
	})
}

// SetMatchPattern sets the "match_pattern" field.
func (u *PromptRuleUpsertBulk) SetMatchPattern(v string) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetMatchPattern(v)
	})
}

// UpdateMatchPattern sets the "match_pattern" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateMatchPattern() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateMatchPattern()
	})
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (u *PromptRuleUpsertBulk) ClearMatchPattern() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearMatchPattern()
	})
}

// SetMatchMode sets the "match_mode" field.
func (u *PromptRuleUpsertBulk) SetMatchMode(v string) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetMatchMode(v)
	})
}

// UpdateMatchMode sets the "match_mode" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateMatchMode() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateMatchMode()
	})
}

// ClearMatchMode clears the value of the "match_mode" field.
func (u *PromptRuleUpsertBulk) ClearMatchMode() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearMatchMode()
	})
}

// SetGroupIds sets the "group_ids" field.
func (u *PromptRuleUpsertBulk) SetGroupIds(v []int64) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetGroupIds(v)
	})
}

// UpdateGroupIds sets the "group_ids" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateGroupIds() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateGroupIds()
	})
}

// ClearGroupIds clears the value of the "group_ids" field.
func (u *PromptRuleUpsertBulk) ClearGroupIds() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearGroupIds()
	})
}

// SetModelIds sets the "model_ids" field.
func (u *PromptRuleUpsertBulk) SetModelIds(v []string) *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.SetModelIds(v)
	})
}

// UpdateModelIds sets the "model_ids" field to the value that was provided on create.
func (u *PromptRuleUpsertBulk) UpdateModelIds() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.UpdateModelIds()
	})
}

// ClearModelIds clears the value of the "model_ids" field.
func (u *PromptRuleUpsertBulk) ClearModelIds() *PromptRuleUpsertBulk {
	return u.Update(func(s *PromptRuleUpsert) {
		s.ClearModelIds()
	})
}

// Exec executes the query.
func (u *PromptRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromptRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
