// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/promptrule"
)

// PromptRuleUpdate is the builder for updating PromptRule entities.
type PromptRuleUpdate struct {
	config
	hooks    []Hook
	mutation *PromptRuleMutation
}

// Where appends a list predicates to the PromptRuleUpdate builder.
func (_u *PromptRuleUpdate) Where(ps ...predicate.PromptRule) *PromptRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptRuleUpdate) SetUpdatedAt(v time.Time) *PromptRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PromptRuleUpdate) SetName(v string) *PromptRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableName(v *string) *PromptRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PromptRuleUpdate) SetDescription(v string) *PromptRuleUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableDescription(v *string) *PromptRuleUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PromptRuleUpdate) ClearDescription() *PromptRuleUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PromptRuleUpdate) SetEnabled(v bool) *PromptRuleUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableEnabled(v *bool) *PromptRuleUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *PromptRuleUpdate) SetOrder(v int) *PromptRuleUpdate {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableOrder(v *int) *PromptRuleUpdate {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *PromptRuleUpdate) AddOrder(v int) *PromptRuleUpdate {
	_u.mutation.AddOrder(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *PromptRuleUpdate) SetRole(v string) *PromptRuleUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableRole(v *string) *PromptRuleUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PromptRuleUpdate) SetContent(v string) *PromptRuleUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableContent(v *string) *PromptRuleUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *PromptRuleUpdate) SetAction(v string) *PromptRuleUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableAction(v *string) *PromptRuleUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMatchPattern sets the "match_pattern" field.
func (_u *PromptRuleUpdate) SetMatchPattern(v string) *PromptRuleUpdate {
	_u.mutation.SetMatchPattern(v)
	return _u
}

// SetNillableMatchPattern sets the "match_pattern" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableMatchPattern(v *string) *PromptRuleUpdate {
	if v != nil {
		_u.SetMatchPattern(*v)
	}
	return _u
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (_u *PromptRuleUpdate) ClearMatchPattern() *PromptRuleUpdate {
	_u.mutation.ClearMatchPattern()
	return _u
}

// SetMatchMode sets the "match_mode" field.
func (_u *PromptRuleUpdate) SetMatchMode(v string) *PromptRuleUpdate {
	_u.mutation.SetMatchMode(v)
	return _u
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_u *PromptRuleUpdate) SetNillableMatchMode(v *string) *PromptRuleUpdate {
	if v != nil {
		_u.SetMatchMode(*v)
	}
	return _u
}

// ClearMatchMode clears the value of the "match_mode" field.
func (_u *PromptRuleUpdate) ClearMatchMode() *PromptRuleUpdate {
	_u.mutation.ClearMatchMode()
	return _u
}

// SetGroupIds sets the "group_ids" field.
func (_u *PromptRuleUpdate) SetGroupIds(v []int64) *PromptRuleUpdate {
	_u.mutation.SetGroupIds(v)
	return _u
}

// AppendGroupIds appends value to the "group_ids" field.
func (_u *PromptRuleUpdate) AppendGroupIds(v []int64) *PromptRuleUpdate {
	_u.mutation.AppendGroupIds(v)
	return _u
}

// ClearGroupIds clears the value of the "group_ids" field.
func (_u *PromptRuleUpdate) ClearGroupIds() *PromptRuleUpdate {
	_u.mutation.ClearGroupIds()
	return _u
}

// SetModelIds sets the "model_ids" field.
func (_u *PromptRuleUpdate) SetModelIds(v []string) *PromptRuleUpdate {
	_u.mutation.SetModelIds(v)
	return _u
}

// AppendModelIds appends value to the "model_ids" field.
func (_u *PromptRuleUpdate) AppendModelIds(v []string) *PromptRuleUpdate {
	_u.mutation.AppendModelIds(v)
	return _u
}

// ClearModelIds clears the value of the "model_ids" field.
func (_u *PromptRuleUpdate) ClearModelIds() *PromptRuleUpdate {
	_u.mutation.ClearModelIds()
	return _u
}

// Mutation returns the PromptRuleMutation object of the builder.
func (_u *PromptRuleUpdate) Mutation() *PromptRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromptRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromptRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promptrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := promptrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromptRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := promptrule.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "PromptRule.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := promptrule.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "PromptRule.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := promptrule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "PromptRule.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchMode(); ok {
		if err := promptrule.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "PromptRule.match_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promptrule.Table, promptrule.Columns, sqlgraph.NewFieldSpec(promptrule.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promptrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(promptrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(promptrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(promptrule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(promptrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(promptrule.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(promptrule.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(promptrule.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(promptrule.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(promptrule.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchPattern(); ok {
		_spec.SetField(promptrule.FieldMatchPattern, field.TypeString, value)
	}
	if _u.mutation.MatchPatternCleared() {
		_spec.ClearField(promptrule.FieldMatchPattern, field.TypeString)
	}
	if value, ok := _u.mutation.MatchMode(); ok {
		_spec.SetField(promptrule.FieldMatchMode, field.TypeString, value)
	}
	if _u.mutation.MatchModeCleared() {
		_spec.ClearField(promptrule.FieldMatchMode, field.TypeString)
	}
	if value, ok := _u.mutation.GroupIds(); ok {
		_spec.SetField(promptrule.FieldGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, promptrule.FieldGroupIds, value)
		})
	}
	if _u.mutation.GroupIdsCleared() {
		_spec.ClearField(promptrule.FieldGroupIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.ModelIds(); ok {
		_spec.SetField(promptrule.FieldModelIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, promptrule.FieldModelIds, value)
		})
	}
	if _u.mutation.ModelIdsCleared() {
		_spec.ClearField(promptrule.FieldModelIds, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promptrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromptRuleUpdateOne is the builder for updating a single PromptRule entity.
type PromptRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromptRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptRuleUpdateOne) SetUpdatedAt(v time.Time) *PromptRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *PromptRuleUpdateOne) SetName(v string) *PromptRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableName(v *string) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PromptRuleUpdateOne) SetDescription(v string) *PromptRuleUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableDescription(v *string) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PromptRuleUpdateOne) ClearDescription() *PromptRuleUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *PromptRuleUpdateOne) SetEnabled(v bool) *PromptRuleUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableEnabled(v *bool) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetOrder sets the "order" field.
func (_u *PromptRuleUpdateOne) SetOrder(v int) *PromptRuleUpdateOne {
	_u.mutation.ResetOrder()
	_u.mutation.SetOrder(v)
	return _u
}

// SetNillableOrder sets the "order" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableOrder(v *int) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetOrder(*v)
	}
	return _u
}

// AddOrder adds value to the "order" field.
func (_u *PromptRuleUpdateOne) AddOrder(v int) *PromptRuleUpdateOne {
	_u.mutation.AddOrder(v)
	return _u
}

// SetRole sets the "role" field.
func (_u *PromptRuleUpdateOne) SetRole(v string) *PromptRuleUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableRole(v *string) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *PromptRuleUpdateOne) SetContent(v string) *PromptRuleUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableContent(v *string) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetAction sets the "action" field.
func (_u *PromptRuleUpdateOne) SetAction(v string) *PromptRuleUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableAction(v *string) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetMatchPattern sets the "match_pattern" field.
func (_u *PromptRuleUpdateOne) SetMatchPattern(v string) *PromptRuleUpdateOne {
	_u.mutation.SetMatchPattern(v)
	return _u
}

// SetNillableMatchPattern sets the "match_pattern" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableMatchPattern(v *string) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetMatchPattern(*v)
	}
	return _u
}

// ClearMatchPattern clears the value of the "match_pattern" field.
func (_u *PromptRuleUpdateOne) ClearMatchPattern() *PromptRuleUpdateOne {
	_u.mutation.ClearMatchPattern()
	return _u
}

// SetMatchMode sets the "match_mode" field.
func (_u *PromptRuleUpdateOne) SetMatchMode(v string) *PromptRuleUpdateOne {
	_u.mutation.SetMatchMode(v)
	return _u
}

// SetNillableMatchMode sets the "match_mode" field if the given value is not nil.
func (_u *PromptRuleUpdateOne) SetNillableMatchMode(v *string) *PromptRuleUpdateOne {
	if v != nil {
		_u.SetMatchMode(*v)
	}
	return _u
}

// ClearMatchMode clears the value of the "match_mode" field.
func (_u *PromptRuleUpdateOne) ClearMatchMode() *PromptRuleUpdateOne {
	_u.mutation.ClearMatchMode()
	return _u
}

// SetGroupIds sets the "group_ids" field.
func (_u *PromptRuleUpdateOne) SetGroupIds(v []int64) *PromptRuleUpdateOne {
	_u.mutation.SetGroupIds(v)
	return _u
}

// AppendGroupIds appends value to the "group_ids" field.
func (_u *PromptRuleUpdateOne) AppendGroupIds(v []int64) *PromptRuleUpdateOne {
	_u.mutation.AppendGroupIds(v)
	return _u
}

// ClearGroupIds clears the value of the "group_ids" field.
func (_u *PromptRuleUpdateOne) ClearGroupIds() *PromptRuleUpdateOne {
	_u.mutation.ClearGroupIds()
	return _u
}

// SetModelIds sets the "model_ids" field.
func (_u *PromptRuleUpdateOne) SetModelIds(v []string) *PromptRuleUpdateOne {
	_u.mutation.SetModelIds(v)
	return _u
}

// AppendModelIds appends value to the "model_ids" field.
func (_u *PromptRuleUpdateOne) AppendModelIds(v []string) *PromptRuleUpdateOne {
	_u.mutation.AppendModelIds(v)
	return _u
}

// ClearModelIds clears the value of the "model_ids" field.
func (_u *PromptRuleUpdateOne) ClearModelIds() *PromptRuleUpdateOne {
	_u.mutation.ClearModelIds()
	return _u
}

// Mutation returns the PromptRuleMutation object of the builder.
func (_u *PromptRuleUpdateOne) Mutation() *PromptRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the PromptRuleUpdate builder.
func (_u *PromptRuleUpdateOne) Where(ps ...predicate.PromptRule) *PromptRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromptRuleUpdateOne) Select(field string, fields ...string) *PromptRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromptRule entity.
func (_u *PromptRuleUpdateOne) Save(ctx context.Context) (*PromptRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptRuleUpdateOne) SaveX(ctx context.Context) *PromptRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromptRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := promptrule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := promptrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PromptRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := promptrule.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "PromptRule.role": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := promptrule.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "PromptRule.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := promptrule.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`ent: validator failed for field "PromptRule.action": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MatchMode(); ok {
		if err := promptrule.MatchModeValidator(v); err != nil {
			return &ValidationError{Name: "match_mode", err: fmt.Errorf(`ent: validator failed for field "PromptRule.match_mode": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptRuleUpdateOne) sqlSave(ctx context.Context) (_node *PromptRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(promptrule.Table, promptrule.Columns, sqlgraph.NewFieldSpec(promptrule.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromptRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, promptrule.FieldID)
		for _, f := range fields {
			if !promptrule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != promptrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(promptrule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(promptrule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(promptrule.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(promptrule.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(promptrule.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Order(); ok {
		_spec.SetField(promptrule.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedOrder(); ok {
		_spec.AddField(promptrule.FieldOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(promptrule.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(promptrule.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(promptrule.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.MatchPattern(); ok {
		_spec.SetField(promptrule.FieldMatchPattern, field.TypeString, value)
	}
	if _u.mutation.MatchPatternCleared() {
		_spec.ClearField(promptrule.FieldMatchPattern, field.TypeString)
	}
	if value, ok := _u.mutation.MatchMode(); ok {
		_spec.SetField(promptrule.FieldMatchMode, field.TypeString, value)
	}
	if _u.mutation.MatchModeCleared() {
		_spec.ClearField(promptrule.FieldMatchMode, field.TypeString)
	}
	if value, ok := _u.mutation.GroupIds(); ok {
		_spec.SetField(promptrule.FieldGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, promptrule.FieldGroupIds, value)
		})
	}
	if _u.mutation.GroupIdsCleared() {
		_spec.ClearField(promptrule.FieldGroupIds, field.TypeJSON)
	}
	if value, ok := _u.mutation.ModelIds(); ok {
		_spec.SetField(promptrule.FieldModelIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedModelIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, promptrule.FieldModelIds, value)
		})
	}
	if _u.mutation.ModelIdsCleared() {
		_spec.ClearField(promptrule.FieldModelIds, field.TypeJSON)
	}
	_node = &PromptRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{promptrule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
